#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header.

sudo apt update
sudo apt install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

NGINX_CONF="/etc/nginx/sites-available/default"
sudo sed -i "/server_name _;/a location \/redirect_me { return 301 https:\/\/github.com\/med-i; }" $NGINX_CONF

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "/server_name _;/a error_page 404 /404.html;" $NGINX_CONF
sudo sed -i "/error_page 404 /a location = /404.html { root /var/www/html; internal; }" $NGINX_CONF

sudo sed -i '/server {/a add_header X-Served-By $hostname;' $NGINX_CONF

sudo service nginx restart
