#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header.

NGINX_CONF='/etc/nginx/sites-available/default'
sudo sed -i '/server {/a \        add_header X-Served-By $hostname;' $NGINX_CONF
sudo service nginx restart
