#!/usr/bin/env bash
# This script configures HAproxy.

sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null

CONFIG_FILE="/etc/haproxy/haproxy.cfg"
sudo cp $CONFIG_FILE{,.original}

sudo tee -a $CONFIG_FILE > /dev/null <<EOT

listen airbnb_clone
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 363623-web-01 52.3.243.59:80 check
    server 363623-web-02 54.237.100.243:80 check
EOT

sudo service haproxy restart
