#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it

mysqldump -u root -p"$1" --all-databases > backup.sql

DATE=$(date +%d-%m-%y)
tar -czvf "$DATE".tar.gz backup.sql

rm backup.sql
