#!/usr/bin/env bash
# pings an IP address passed as an argument.
if [ "$#" -eq 1 ]; then
    ip_address="$1"
    ping -c 5 "$ip_address"
else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
