#!/usr/bin/env bash
# Manages the "manage_my_process" script.

SCRIPT="./manage_my_process"
PID="/var/run/my_process.pid"

case "$1" in
	start)
		$SCRIPT &
		echo $! > $PID
		echo "manage_my_process started"
		;;
	stop)
		kill "$(cat $PID)"
		rm -f $PID
		echo "manage_my_process stopped"
		;;

	restart)
		kill "$(cat $PID)"
		rm -f $PID
		$SCRIPT &
		echo $! > $PID
		echo "manage_my_process restarted"
		;;

	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac

