#!/usr/bin/env bash
# displays the content of the file /etc/passwd.
while read -r line; do
	username=$(echo "$line" | cut -d ':' -f1)
	userid=$(echo ":$line" | cut -d ':' -f2)
	userhome=$(echo ":$line" | cut -d ':' -f6)

	echo -n "$username:"
	echo -n "$userid:"
	echo "/$userhome"
done < /etc/passwd
