#!/usr/bin/env bash
# displays the content of the file /etc/passwd, using the while loop + IFS.
while IFS=: read -r username password user_id group_id user_info home_dir login_shell; do
	echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $login_shell. $user_id's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd
