#!/usr/bin/env bash
# loops from 1 to 10 and displays stuff.
for ((i = 1; i <= 10; i++)); do
	if (( i == 4)); then
		echo "bad luck"
	elif (( i == 8)); then
		echo "good luck"
	else
		echo "Best School"
	fi
done
