#!/usr/bin/env bash
# displays numbers from 1 to 20 and specific sentences for some iterations.
for ((i = 1; i <= 20; i++)); do
	echo "$i"

	if ((i == 4)); then
		echo "bad luck from China"
	elif ((i == 9)); then
		echo "bad luck from Japan"
	elif ((i == 17)); then
		echo "bad luck from Italy"
	fi
done
