#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements.
cp /etc/hosts ~/hosts.new
sed -i "/localhost$/d" ~/hosts.new
sed -i "/facebook.com$/d" ~/hosts.new
echo "127.0.0.2 localhost" >> ~/hosts.new
echo "8.8.8.8   facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm -f ~/hosts.new